language: scala
scala:
- 2.11.7
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - kinjacono@yahoo.co.uk
env:
  global:
  - secure: k/cpuJ0m4PyiYKOfPCKWe7YUsB6gKZHE4vVvWfUr/l55Jz1codBnOehHzeeruqZyyHfg85K/ZPNKM3jciFdoME4SgWX0FhinLFfrkzC+zZNweaXNJXRdiH4n9cINUYxjDWX8FxuIoGxvIWJZpu44u/qbK6ZctCi21m6iAX8hST527tr9NcYxhbK8fAJ6sGUqqvpItC/CTaLWYoPaNEpyjOkNZK8s2tNM/ECVTCkv+m+BGDfA0zStYbnBeDX9LZKo/YWdBUSQg3edYNezhSFZbjdk9gjnWtEjKC1nvdWDor/VEurXGWNQAkG347ZWhFUp2D0Gq7FSJbnsHpS+f6C59w+ar2GKoCFEd4OWyy7106Gkpb49M9g5OM6z/QMBFuHzfFzjTpmYC783nXDDx+1hD6k0TPC+XeyFzjiQErvhp1wdEqZqgiNIDuIWWRQk5Eb46y9l3nBGOZ7Uv8bH8jeTlouOByYoju4Q6WMcjYIiGx5DbtshdGg6Isb9rK8NB2sTTDJmAYgcQ/8pRLh4Z8boKkHwmQnOYppdGsqHIigJdxbIocm4C29t9PLS+bWT6GvOedKuyqHiRGWSTpxVlC7hY2JxJAWbIQoZAwC5e9U9lfIK4Q1bZ4z9fBtIJzT1tXQ5CvJSvyUABcHXPWJXYkjrvbcs5KFcH4hDGAnJB0QQ0HM=
  - secure: 4gL6TyG3VkahJwlHuI2s0/VXeB+7WrBxrRZfZNYxd5JkIF4W0J/B41Aj3bToQJ/7zDe90Nr4by4mEahP4aLBJVT8rvPs+84jRnBsQXhjHm3ym5iPnqsnElnI/ay3Ti2Z9/JhXequU7Cttdtj3VUZSjwZiEYZ5fE8J/89pGdhvJDocxzhGP3HNBrILdzNgqaKU6qiuQzTsyh9nVgS1PlxYt45cTXivvDS83VONilcsAbbQy7reGnmKhXPY2uTB0s2gRyZvoeCgESHvBhu9kmyhltqTSdrx/SkLgMhk6UlMDhGe54rBmGzoRi+QgIdc5aDJD+ncoV/IbJy2sGK/cyUL53fTpSKLw1PjPfMIc1c/6C7olURBFKFNkGpN24NeqXhfDufeS3FEiZir3IhVlGI/I1r7kLfX01QoXfKVdv+8o0i1zXo/+pkXOfMjK84VoWOd5wf1CC71CxHdbarkyVkWHCfO7y4j+YYH278yPg74XbJez6enWa43dLddLkDViOEAAYihv/n4G31sBdULEymRFM5KTOgmBe4+/Dj+GW3sfivpDpQc6QkeNRMRTezfWbSe+kn3yIGw9GSvA/U6YrL5ovYks7Lf2vD0s7FCVdCEwD69rPmmbCsTRaQDS86MadgvfXwcQA2kujXtpcoOjspQLeGwwTtIkKOugKuv3lAP9A=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
